owner: yillkid
repo: upptime-monitor

# Target sites
sites:
  - name: PoE server
    method: GET
    url: https://poe.townway.com.tw/iota/message?messageID=42a2685d98d11bfb336d0928ce1e49cf3c85f5f2f075f5028fc1ea29497a1c67
    headers:
      - "Authorization: ${{ secrets.POE_API_KEY }}"
  - name: Node1 upptime test
    url: http://node1.puyuma.org:5002

# Workflow schedule
workflowSchedule:
  graphs: "0 0 * * *"
  responseTime: "0 23 * * *"
  staticSite: "0 1 * * *"
  summary: "0 0 * * *"
  updateTemplate: "0 0 * * *"
  updates: "0 3 * * *"
  uptime: "*/5 * * * *"

# Slack notify
NOTIFICATION_SLACK: ${{ secrets.NOTIFICATION_SLACK }}
NOTIFICATION_SLACK_WEBHOOK: ${{ secrets.NOTIFICATION_SLACK_WEBHOOK }}
NOTIFICATION_SLACK_WEBHOOK_URL: ${{ secrets.NOTIFICATION_SLACK_WEBHOOK_URL }}
